### PR TITLE
Used IDE CS on ALL the code 

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Used https://github.com/wmde/intellij-settings

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
> The real value of such changes comes from the rules for automatic enforcement they should bring along with them - without them the, now perceived pristine, state will quickly erode again.

I have a different view. What I'd like to be able to do is hit a IDE hotkey and have the code I just wrote be formatted in an acceptable manner. Right now I'm often, while writing the code, spending keystrokes on adding the space I forgot. This wastes time, is a constant drain of attention and breaks flow. I made this PR for two related reasons:

* Fix existing deviations from agreed upon CS that are not caught by our CS checkers.
* Have the code in a form that is at least close to the used IDE style, so that formatting some code after adding something does not change everything

This PR contains changes that I think are not needed. For instance putting every function call on its own line is not something I think is needed. And not what the IDE is doing I think - it just does it in some cases, some of which I think where fine, or even slightly better, with the stuff being on the same line. To me this is not a problem, since I would not object to new code written with one call per line. And since I am fine with both forms, I see no need to enforce whatever the IDE happens to be doing now with style checks.

In some cases it is great to have style checks. `[1, 2]` vs `[ 1, 2 ]` being a good example. Actually I think we had a check for that at some point, since it is a well established part of the MediaWiki/WMDE CS, but lost the check when switching to PHP 7 due to some compat issue. At the same time I think I'd be counter productive to try have a check for everything the IDE changes. What the IDE does is naturally going to be very well specified, and will fall somewhere in the space of acceptable CS. No need to reduce that space to just what the IDE does.

**Comment by JeroenDeDauw** [comment]
> every function call on separate line. +1, helps readability

I think this is not every function call, but cases where the length of the line is too long, or where multiple arguments are already on multiple lines. While I find what the IDE did acceptable, sometimes it seems a bit silly.

**Comment by JeroenDeDauw** [comment]
> try bracket and catch, if bracket and else on separate lines. -1, waste of space

I changed the else case. For catch I actually prefer the new line, since the line itself contains more than just a bracket and keywords. I'm totally fine with both forms in code though. Thing is we need to pick something for the IDE formatting rules. It has no "leave as is" option here :( Do you object to merging the PR as is?

> multiple opening brackets not on one line. -1, I'd rather not

I just looked at the rules again and do not know how to avoid this. It looks like unless you disable the nice multiline behavior altogether, this is what will happen. To me the benefit of the multi-line stuff outweighs the silliness of how it behaves in this case. Agree?

**Comment by JeroenDeDauw** [comment]
> anon function declaration w/o space. 0, ok

I actually did the reverse of what Nikerabbit recommended now, since this is not very consistent:

    function noSpaceHere() {}
    $whySpace = function () {}

One function declaration has a space and the other one does not...

**Comment by wiese** [comment]
The changes are fair.

However, I maintain that "rules" that are not part of automated linting, even if they are configured inside an IDE, are easy to violate (think 3rd party PR), cumbersome to enforce (follow-up PR?), in-transparent (are we linking https://github.com/wmde/intellij-settings in the README and ban other editors?), and as such grounds for endless pseudo-religious dispute.

I am not saying that this should not be merged, but rather that it has a lot of lost potential of changes that should come along with it.

**Comment by JeroenDeDauw** [comment]
I agree with what you wrote. Thing is that to me there are no rules added by this PR. If you diverge somehow and it still passes the CS that is entirely fine. (With some exceptions such as the array spacing, but that was already the case before. Not an ideal situation, though not affected by this PR, beyond that it becomes easier to fix those violations if your IDE does it automatically.) So yeah, if we enforced exactly this style without automatically checking it, that'd be problematic, but then no one I prosing we do that.

>  it has a lot of lost potential of changes that should come along with it.

raise new ParseError();

**Comment by JeroenDeDauw** [comment]
Much Merge?

**Pull request merged**
